# Generated by Django 4.1.1 on 2022-12-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['date'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
