# Generated by Django 3.2.16 on 2023-01-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_alter_certificate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='score',
        ),
    ]
