# Generated by Django 3.2.16 on 2023-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_delete_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
