# Generated by Django 3.2.16 on 2023-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_alter_portfolio_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
    ]
