# Generated by Django 3.2.16 on 2023-01-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
