# Generated by Django 4.1.6 on 2023-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0013_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
    ]
