# Generated by Django 4.1.6 on 2023-03-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0014_alter_contactprofile_message_alter_media_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
